import { EducationalAsset } from './educationalLibrary';

export const ENCYCLOPEDIA_LIBRARY: EducationalAsset[] = [
    // Nature
    { keywords: ['volcano', 'lava', 'magma', 'eruption'], path: 'assets/educational/encyclopedia/Nature/volcano.svg' },
    { keywords: ['mountain', 'peak', 'hill', 'summit'], path: 'assets/educational/encyclopedia/Nature/mountain.svg' },
    { keywords: ['desert', 'sand', 'dry', 'sahara'], path: 'assets/educational/encyclopedia/Nature/desert.svg' },
    { keywords: ['island', 'beach', 'tropical', 'coast'], path: 'assets/educational/encyclopedia/Nature/island.svg' },
    { keywords: ['river', 'lake', 'national park', 'waterway'], path: 'assets/educational/encyclopedia/Nature/national_park.svg' },
    { keywords: ['ocean', 'sea', 'waves', 'marine', 'water'], path: 'assets/educational/encyclopedia/Nature/ocean_wave.svg' },
    { keywords: ['rainbow', 'colors', 'sky', 'spectrum'], path: 'assets/educational/encyclopedia/Nature/rainbow.svg' },
    { keywords: ['sun', 'sunny', 'daylight', 'star', 'solar'], path: 'assets/educational/encyclopedia/Nature/sun.svg' },
    { keywords: ['moon', 'full moon', 'night', 'lunar'], path: 'assets/educational/encyclopedia/Nature/moon_full.svg' },
    { keywords: ['star', 'twinkle', 'universe', 'cosmos'], path: 'assets/educational/encyclopedia/Nature/star.svg' },
    { keywords: ['comet', 'asteroid', 'meteor', 'space rock'], path: 'assets/educational/encyclopedia/Nature/comet.svg' },
    { keywords: ['earth', 'world', 'planet', 'globe'], path: 'assets/educational/encyclopedia/Nature/earth.svg' },
    { keywords: ['cloudy', 'partly cloudy', 'weather'], path: 'assets/educational/encyclopedia/Nature/cloud_sun.svg' },
    { keywords: ['rainy', 'raining', 'shower', 'storm'], path: 'assets/educational/encyclopedia/Nature/cloud_rain.svg' },
    { keywords: ['lightning', 'thunderstorm', 'bolt', 'flash'], path: 'assets/educational/encyclopedia/Nature/lightning.svg' },

    // Space
    { keywords: ['rocket', 'launch', 'shuttle', 'spaceship'], path: 'assets/educational/encyclopedia/Space/rocket.svg' },
    { keywords: ['satellite', 'orbit', 'gps', 'broadcast'], path: 'assets/educational/encyclopedia/Space/satellite.svg' },
    { keywords: ['astronaut', 'spacewalk', 'cosmonaut', 'helmet'], path: 'assets/educational/encyclopedia/Space/astronaut.svg' },
    { keywords: ['telescope', 'astronomy', 'universe', 'view'], path: 'assets/educational/encyclopedia/Space/telescope.svg' },

    // Animals
    { keywords: ['lion', 'roar', 'mane', 'safari'], path: 'assets/educational/encyclopedia/Animals/lion.svg' },
    { keywords: ['tiger', 'stripes', 'feline', 'jungle'], path: 'assets/educational/encyclopedia/Animals/tiger.svg' },
    { keywords: ['elephant', 'trunk', 'tusk', 'mammoth'], path: 'assets/educational/encyclopedia/Animals/elephant.svg' },
    { keywords: ['giraffe', 'long neck', 'spots', 'savanna'], path: 'assets/educational/encyclopedia/Animals/giraffe.svg' },
    { keywords: ['zebra', 'stripes', 'horse-like', 'africa'], path: 'assets/educational/encyclopedia/Animals/zebra.svg' },
    { keywords: ['monkey', 'ape', 'primate', 'climb'], path: 'assets/educational/encyclopedia/Animals/monkey.svg' },
    { keywords: ['wolf', 'howl', 'pack', 'canine'], path: 'assets/educational/encyclopedia/Animals/wolf.svg' },
    { keywords: ['fox', 'clever', 'red fox', 'vixen'], path: 'assets/educational/encyclopedia/Animals/fox.svg' },
    { keywords: ['panda', 'bamboo', 'black and white', 'bear'], path: 'assets/educational/encyclopedia/Animals/panda.svg' },
    { keywords: ['koala', 'eucalyptus', 'australia', 'marsupial'], path: 'assets/educational/encyclopedia/Animals/koala.svg' },
    { keywords: ['kangaroo', 'pouch', 'hop', 'australia'], path: 'assets/educational/encyclopedia/Animals/kangaroo.svg' },
    { keywords: ['eagle', 'raptor', 'bird of prey', 'hawk'], path: 'assets/educational/encyclopedia/Animals/eagle.svg' },
    { keywords: ['owl', 'bird', 'night', 'hoot', 'wise'], path: 'assets/educational/encyclopedia/Animals/owl.svg' },
    { keywords: ['penguin', 'antarctica', 'ice', 'waddle', 'bird'], path: 'assets/educational/encyclopedia/Animals/penguin.svg' },
    { keywords: ['parrot', 'tropical bird', 'wings', 'feathers'], path: 'assets/educational/encyclopedia/Animals/parrot.svg' },
    { keywords: ['shark', 'fin', 'jaws', 'ocean predator'], path: 'assets/educational/encyclopedia/Animals/shark.svg' },
    { keywords: ['whale', 'marine mammal', 'ocean', 'heavy'], path: 'assets/educational/encyclopedia/Animals/whale.svg' },
    { keywords: ['fish', 'swim', 'scales', 'gills'], path: 'assets/educational/encyclopedia/Animals/fish.svg' },
    { keywords: ['octopus', 'eight legs', 'ink', 'marine'], path: 'assets/educational/encyclopedia/Animals/octopus.svg' },
    { keywords: ['butterfly', 'insect', 'wings', 'larva'], path: 'assets/educational/encyclopedia/Animals/butterfly.svg' },
    { keywords: ['bee', 'honey', 'pollen', 'stinger'], path: 'assets/educational/encyclopedia/Animals/bee.svg' },
    { keywords: ['spider', 'web', 'eight legs', 'arachnid'], path: 'assets/educational/encyclopedia/Animals/spider.svg' },
    { keywords: ['cat', 'kitten', 'pussycat', 'meow', 'pet'], path: 'assets/educational/encyclopedia/Animals/cat.svg' },
    { keywords: ['dog', 'puppy', 'bark', 'pet', 'canine'], path: 'assets/educational/encyclopedia/Animals/dog.svg' },
    { keywords: ['rabbit', 'bunny', 'hare', 'ears'], path: 'assets/educational/encyclopedia/Animals/rabbit.svg' },
    { keywords: ['turtle', 'shell', 'slow', 'reptile'], path: 'assets/educational/encyclopedia/Animals/turtle.svg' },
    { keywords: ['snake', 'reptile', 'coil', 'venom'], path: 'assets/educational/encyclopedia/Animals/snake.svg' },
    { keywords: ['frog', 'amphibian', 'jump', 'croak'], path: 'assets/educational/encyclopedia/Animals/frog.svg' },

    // Science & Anatomy
    { keywords: ['brain', 'thinking', 'nervous system', 'mind', 'intellect'], path: 'assets/educational/encyclopedia/Science_Anatomy/brain.svg' },
    { keywords: ['heart', 'pulse', 'simple heart', 'love', 'cardiac'], path: 'assets/educational/encyclopedia/Science_Anatomy/heart_simple.svg' },
    { keywords: ['bone', 'skeleton', 'anatomy', 'calcium'], path: 'assets/educational/encyclopedia/Science_Anatomy/bone.svg' },
    { keywords: ['tooth', 'dentist', 'enamel', 'bite'], path: 'assets/educational/encyclopedia/Science_Anatomy/tooth.svg' },
    { keywords: ['eye', 'vision', 'sight', 'cornea'], path: 'assets/educational/encyclopedia/Science_Anatomy/eye.svg' },
    { keywords: ['ear', 'hearing', 'audio', 'canal'], path: 'assets/educational/encyclopedia/Science_Anatomy/ear.svg' },
    { keywords: ['microscope', 'lab', 'cells', 'magnify', 'science'], path: 'assets/educational/encyclopedia/Science_Anatomy/microscope.svg' },
    { keywords: ['magnet', 'poles', 'north south', 'magnetic', 'attraction'], path: 'assets/educational/encyclopedia/Science_Anatomy/magnet.svg' },
    { keywords: ['battery', 'voltage', 'power', 'cell', 'dc'], path: 'assets/educational/encyclopedia/Science_Anatomy/battery.svg' },
    { keywords: ['bulb', 'light', 'electricity', 'filament', 'idea'], path: 'assets/educational/encyclopedia/Science_Anatomy/bulb.svg' },
    { keywords: ['gear', 'mechanical', 'machine', 'cogs', 'work'], path: 'assets/educational/encyclopedia/Science_Anatomy/gear.svg' },

    // Math & Shapes
    { keywords: ['square', 'rect', 'four sides'], path: 'assets/educational/encyclopedia/Math_Shapes/square_black.svg' },
    { keywords: ['circle', 'round', 'loop'], path: 'assets/educational/encyclopedia/Math_Shapes/circle_black.svg' },
    { keywords: ['triangle', 'delta', 'three sides'], path: 'assets/educational/encyclopedia/Math_Shapes/triangle_up.svg' },
    { keywords: ['ruler', 'math ruler', 'measure', 'triangle ruler'], path: 'assets/educational/encyclopedia/Math_Shapes/ruler_triangle.svg' },
    { keywords: ['straight ruler', 'length', 'cm', 'inches'], path: 'assets/educational/encyclopedia/Math_Shapes/ruler_straight.svg' },
    { keywords: ['numbers', 'math numbers', '1234', 'digits'], path: 'assets/educational/encyclopedia/Math_Shapes/numbers_1234.svg' },
    { keywords: ['fractions', 'math fractions', 'pizza slices', 'parts'], path: 'assets/educational/encyclopedia/Math_Shapes/fractions_pizza.svg' },

    // History & Civics
    { keywords: ['pyramid', 'egypt', 'ancient monunment', 'giza'], path: 'assets/educational/encyclopedia/History_Civics/pyramid_monument.svg' },
    { keywords: ['statue of liberty', 'usa', 'landmark', 'freedom'], path: 'assets/educational/encyclopedia/History_Civics/statue_of_liberty.svg' },
    { keywords: ['castle', 'fort', 'knights', 'medieval'], path: 'assets/educational/encyclopedia/History_Civics/castle.svg' },
    { keywords: ['tower', 'monument', 'landmark'], path: 'assets/educational/encyclopedia/History_Civics/tokyo_tower.svg' },
    { keywords: ['book', 'knowledge', 'encyclopedia', 'reading'], path: 'assets/educational/encyclopedia/History_Civics/book_open.svg' },
    { keywords: ['justice', 'scales', 'balance', 'law', 'legal'], path: 'assets/educational/encyclopedia/History_Civics/scales_justice.svg' },
    { keywords: ['voting', 'ballot', 'democracy', 'election'], path: 'assets/educational/encyclopedia/History_Civics/ballot_box.svg' },
    { keywords: ['greek building', 'ancient building', 'architecture', 'temple'], path: 'assets/educational/encyclopedia/History_Civics/classical_building.svg' },

    // Objects & Transport
    { keywords: ['car', 'auto', 'vehicle', 'drive'], path: 'assets/educational/encyclopedia/Objects_Transport/car.svg' },
    { keywords: ['bus', 'city bus', 'school bus'], path: 'assets/educational/encyclopedia/Objects_Transport/bus.svg' },
    { keywords: ['train', 'engine', 'steam train'], path: 'assets/educational/encyclopedia/Objects_Transport/train.svg' },
    { keywords: ['airplane', 'jet', 'fly', 'flight'], path: 'assets/educational/encyclopedia/Objects_Transport/airplane.svg' },
    { keywords: ['ship', 'boat', 'ocean vessel'], path: 'assets/educational/encyclopedia/Objects_Transport/ship.svg' },
    { keywords: ['bicycle', 'cycling', 'pedals'], path: 'assets/educational/encyclopedia/Objects_Transport/bicycle.svg' },
    { keywords: ['computer', 'laptop', 'logic box', 'screen'], path: 'assets/educational/encyclopedia/Objects_Transport/computer.svg' },
    { keywords: ['phone', 'mobile', 'smartphone', 'call'], path: 'assets/educational/encyclopedia/Objects_Transport/phone.svg' },
    { keywords: ['bed', 'sleep', 'bedroom', 'mattress'], path: 'assets/educational/encyclopedia/Objects_Transport/bed.svg' },
    { keywords: ['chair', 'seat', 'furniture'], path: 'assets/educational/encyclopedia/Objects_Transport/chair.svg' },
    { keywords: ['school', 'education', 'classroom building'], path: 'assets/educational/encyclopedia/Objects_Transport/school_building.svg' },
    { keywords: ['house', 'home', 'residence'], path: 'assets/educational/encyclopedia/Objects_Transport/house_building.svg' }
];
